# Generated by Django 2.2.5 on 2019-12-08 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, unique=True)),
                ('course_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_name', models.CharField(max_length=200)),
                ('hr_username', models.CharField(max_length=200, unique=True)),
                ('hr_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(auto_created=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_address', models.CharField(max_length=250)),
                ('user_mobile', models.IntegerField()),
                ('user_doj', models.DateTimeField(default=datetime.date(2019, 12, 8))),
                ('user_email', models.CharField(max_length=200)),
                ('user_username', models.CharField(max_length=200, unique=True)),
                ('user_password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('user_payment', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(auto_created=True)),
                ('trainer_name', models.CharField(max_length=200)),
                ('trainer_mobile', models.IntegerField()),
                ('trainer_doj', models.DateTimeField(default=datetime.date(2019, 12, 8))),
                ('trainer_email', models.CharField(max_length=200)),
                ('trainer_username', models.CharField(max_length=200, unique=True)),
                ('trainer_password', models.CharField(max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('role_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Role')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_flag', models.IntegerField(default=0)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_date', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_data', models.CharField(max_length=250)),
                ('feedback_date', models.DateTimeField(default=datetime.date(2019, 12, 8))),
                ('feedback_comment', models.CharField(max_length=350, null=True)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Batch')),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Trainer')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Course'),
        ),
    ]
