# Generated by Django 2.2.5 on 2019-12-09 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=datetime.date(2019, 12, 9)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 9)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 9)),
        ),
    ]
