# Generated by Django 2.2.5 on 2019-12-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20191209_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/default.jpeg', upload_to='profile_image/'),
        ),
    ]
