
# Generated by Django 2.2.5 on 2019-12-10 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20191209_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainer_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 10)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 10)),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
