# Generated by Django 2.2.5 on 2019-12-13 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20191212_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=datetime.date(2019, 12, 13)),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 13)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_doj',
            field=models.DateTimeField(default=datetime.date(2019, 12, 13)),
        ),
    ]
